# Generated by Django 4.2.7 on 2024-01-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allusers01",
            name="amount",
            field=models.IntegerField(),
        ),
    ]
